# https://github.com/sindresorhus/appveyor-node/blob/master/appveyor.yml

environment:
  matrix:
    - platform: x32
  GH_TOKEN:
    secure: 2715c20dc6f96753850ee30aab3c0af11deefe56

cache:
  - node_modules

install:
  - node --version
  - npm --version
  - npm install

build: on

test_script:
  - npm run build
